wip

diff --git a/shell/functions b/shell/functions
--- a/shell/functions
+++ b/shell/functions
@@ -44,9 +44,48 @@ function update_completions() {
     talosctl_completion
 }
 
-# Create dmg file of folder
-function dmg() {
-    hdiutil create -skipunreadable -fs APFS -format UDRO -srcfolder "$1" -volname "$2" "$2.dmg"
+function backup_home() {
+    ANYFAIL=false
+    log_task "Creating Backup"
+
+    mkdir -p $HOME/Backup/_temp
+
+    log_task "Copying files" \
+        && rsync --info=progress2 --no-i-r -avr \
+            --exclude="Library" \
+            --exclude="Movies" \
+            --exclude="Music" \
+            --exclude="Pictures/Photos Library.photoslibrary" \
+            --exclude="Downloads" \
+            --exclude="Backup" \
+            --exclude=".config/colima" \
+            --exclude=".k8slens" \
+            --exclude=".krew" \
+            --exclude=".kube/cache" \
+            --exclude=".vscode/extensions" \
+            --exclude=".Trash" \
+            --exclude="*/.DS_Store" \
+            --exclude="*/*.sock" \
+            $HOME $HOME/Backup/_temp | grep -o "[0-9]*%" | sed 's/%//' | progressBar | log_progress  \
+        && log_task_success \
+        || (log_task_fail && ANYFAIL=true)
+
+    log_task "Creating DMG" \
+        && dmg $(date "+%Y-%m") "$HOME/Backup/_temp/$(whoami)" "$HOME/Backup/" | progressbar | log_progress \
+        && log_task_success \
+        || (log_task_fail && ANYFAIL=true)
+
+    log_task "Cleaning up" \
+        && rm -rf mkdir -p $HOME/Backup/_temp \
+        && log_info "Temporary files removed" \
+        && log_task_success \
+        || (log_task_fail && ANYFAIL=true)
+
+    if [ "$ANYFAIL" = true ]; then
+        log_task_fail "Backup failed"
+    else
+        log_task_success "$HOME/Backup/$(date "+%Y-%m").dmg"
+    fi
 }
 
 # List open media
@@ -206,6 +245,72 @@ function datetime2date() {
             fi
         done
     fi
+}
+
+function log_progress() {
+    symbolEmpty="⠀"
+    symbolFull="⠿"
+    if ! [ -t 0 ]; then
+        i=1
+
+        symbol=$symbolEmpty
+        printf "${TXT_GRAY}$(get_current_time)${TXT_CLEAR} ${TXT_BLUE}$(get_log_indents)${symbol} $(echo 0 | progressBar)${TXT_CLEAR}\r";
+        
+        while IFS= read -r line; do
+            case $((i % 10)) in
+                0) symbol="⠋" ;;
+                1) symbol="⠙" ;;
+                2) symbol="⠹" ;;
+                3) symbol="⠸" ;;
+                4) symbol="⠼" ;;
+                5) symbol="⠴" ;;
+                6) symbol="⠦" ;;
+                7) symbol="⠧" ;;
+                8) symbol="⠇" ;;
+                9) symbol="⠏" ;;
+            esac
+
+            printf "${TXT_GRAY}$(get_current_time)${TXT_CLEAR} ${TXT_BLUE}$(get_log_indents)${symbol} ${line}${TXT_CLEAR}\r";
+            i=$((i+1))
+        done
+
+        symbol=$symbolFull
+        printf "${TXT_GRAY}$(get_current_time)${TXT_CLEAR} ${TXT_BLUE}$(get_log_indents)${symbol} $(echo 100 | progressBar)${TXT_CLEAR}\r\n";
+    fi
+}
+
+function render_script() {
+    file=$1
+
+    template=$(cat $file)
+
+    for i in "$@"; do
+        case $i in
+            -r=*|--replace=*)
+            search=$(echo ${i#*=} | awk -F'=' '{print $1}')
+            replace=$(echo ${i#*=} | awk -F'=' '{print $2}')
+
+            template=$(echo "$template" | sed "s/$search/$replace/g")
+            shift
+            ;;
+            *)
+            ;;
+        esac
+    done
+
+    echo "$template"
+}
+
+function test-connection-nc() {
+    render_script $HOME/.dotfiles/kubernetes/test-connection-nc.sh \
+        -r=IPS="$1" \
+        -r=PORTS="$2"
+}
+
+function test-connection-pg() {
+    render_script $HOME/.dotfiles/kubernetes/test-connection-pg.sh \
+        -r=IPS="$1" \
+        -r=PORTS="$2"
 }
 
 # zmk_build <build-dir> <board> <shield>
